---
title: "LoaLoa_contiglength_blast"
author: "Sofia Roitman"
date: "4/1/2022"
output: html_document
---

# Set working directory
```{r}
setwd("/path/to/wd")
```

# Load in data files
```{r}
# Data file
## Contains: contig name, length, # reads mapped, # reads unmapped
blast = read.table("trinity_cdhit95_nemaplaty_aln_LoaLoa_contigsonly.txt", header = TRUE)
lengths = read.table("trinity_cdhit95_kraken2_LoaLoa_contig_lengths.txt", header = TRUE, sep = '\t')

```
# Merge tables by query/contig_id
```{r}
library(dplyr)

df_merge <- merge(blast, lengths, by="contig_id")
```

# Add in aln_perc
```{r}
# So the operation should be: aln_length/length = aln_perc

df_merge$aln_perc <- df_merge$aln_length / df_merge$length
```


# Histogram: alignment %
```{r}
library(ggplot2)
loa_histo <- ggplot(df_merge, aes(x=aln_perc)) + geom_histogram() 

pdf("PRJNA289926_loa_histo.pdf") 
# 2. Create a plot
loa_histo
# Close the pdf file
dev.off() 

```

# Scatterplot: alignment % vs. identity %
```{r}
ggplot(df_merge, aes(x=length, y=X._id)) + geom_point(size=2, color = "blue")
loa_scatter <- ggplot(df_merge, aes(x=aln_perc, y=X._id, size=length)) + geom_point(color = "blue")

pdf("loa_scatter.pdf") 
# 2. Create a plot
loa_scatter
# Close the pdf file
dev.off() 

```
# Create dataframe containing anything with aln_perc < 0.75
```{r}

stats_0.75 <- df_merge[ which(df_merge$aln_perc < 0.75),]
stats_over_0.75 <- df_merge[ which(df_merge$aln_perc > 0.75),]
write.csv(stats_0.75, file = "nema_platy_aln_LoaLoa_0.75_aln_perc.csv")
write.csv(stats_over_0.75, file = "nema_platy_aln_LoaLoa_over_0.75_aln_perc.csv")

```




